CREATE TABLE IF NOT EXISTS User (
    Id int NOT NULL AUTO_INCREMENT,
    Name varchar(255) NOT NULL,
    Email varchar(255) NOT NULL,
    Password varchar(255) NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;