CREATE TABLE IF NOT EXISTS Task (
    Id int NOT NULL AUTO_INCREMENT,
    Title varchar(255) NOT NULL,
    Body varchar(255) NOT NULL,
    Status tinyint(1) NOT NULL DEFAULT '0',
    UserId int NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES User(Id),
    PRIMARY KEY (Id)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;